### ISSUE TITLE
TMBdebug does not install with remotes::install_github()

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [kaskr/TMB_contrib_R#9]
Trying:

    remotes::install_github("kaskr/TMB_contrib_R/TMBdebug")

gives an error: 
Error : (converted from warning) ... TMBdebug/man/TMBdebug-package.Rd:26: All text must be in a section

This is caused by line 26 in   'TMB_contrib_R/TMBdebug/man/TMBdebug-package.Rd' not being in a section:
 ~~ Optionally other standard keywords, one per line, from file KEYWORDS in the R documentation directory ~~

There are also other informational lines (starting with '~~') within unused sections that could removed.

**Comment by mkapur** [comment]
I am having this same issue, and noticed that @John-R-Wallace-NOAA had created a standalone version of this package but I also could not get that to install via `remotes`. I'm not sure if anyone is monitoring/checking on this issue, and noticed that a post in the [google user groups](https://groups.google.com/g/tmb-users/c/X48AHCVOpKg?pli=1) went unanswered -- @marksorel8 did you receive any private responses from that thread?

**Comment by mkapur** [comment]
Thanks to assistance from @John-R-Wallace-NOAA, the following appear to be two alternative solutions:
1) Updating to R v4.1.2, whereupon the warning thrown due to unaligned text in the `.Rd` is **not** converted to an error, and installation proceeds normally, or
2)  If sticking with Rv4.0.3, can use `remotes::install_github("John-R-Wallace-NOAA/TMB-debug")`, where John has made the appropriate text changes to avoid the "out of section" error.

**Comment by Cole-Monnahan-NOAA** [comment]
@John-R-Wallace-NOAA why not a PR to merge yours back in to the official one? Sounds like you've got it worked out and tested by a couple people already. Would be helpful I think

**Comment by John-R-Wallace-NOAA** [comment]
Pull requested
